version: '3'

services:
  spark_etl_template:
    build: .
    volumes:
      - ./src/:/app/src/
      - ./tests/:/app/tests/
      - ./input/:/app/input/
      - ./output/:/app/output/
      - ./mypy.ini:/app/mypy.ini
    command: tail -f /dev/null